### ISSUE TITLE
Issue while migrating DB

### ISSUE THREAD

**Issue by hideodaikoku** [keio-moe/song-test-api#18]
Issue while running

`rake db migrate`

```
rake aborted!
Sequel::DatabaseConnectionError: SQLite3::CantOpenException: unable to open database file
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:89:in `open_v2'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:89:in `initialize'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:114:in `new'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:114:in `connect'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool.rb:122:in `make_new'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:278:in `test_connection'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/misc.rb:169:in `initialize'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:57:in `new'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:57:in `connect'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/core.rb:124:in `connect'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/initializers/sequel.rb:2:in `<top (required)>'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/Rakefile:25:in `require'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/Rakefile:25:in `block in <top (required)>'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/Rakefile:21:in `<top (required)>'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/compmusic/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/compmusic/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
SQLite3::CantOpenException: unable to open database file
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:89:in `open_v2'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:89:in `initialize'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:114:in `new'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/adapters/sqlite.rb:114:in `connect'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool.rb:122:in `make_new'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:278:in `test_connection'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/misc.rb:169:in `initialize'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:57:in `new'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/database/connecting.rb:57:in `connect'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/sequel-5.41.0/lib/sequel/core.rb:124:in `connect'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/initializers/sequel.rb:2:in `<top (required)>'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/Rakefile:25:in `require'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/Rakefile:25:in `block in <top (required)>'
/Users/compmusic/Documents/Work/Yamaha/song-test-api/Rakefile:21:in `<top (required)>'
/Users/compmusic/.rvm/gems/ruby-3.0.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/compmusic/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/compmusic/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by dsh0416** [comment]
Create the `db` folder first when using the default development database configuration.
